django/urlCoading_django_project/myUrl/codingUrl/urls.py
from django.urls import path
from codingUrl import views

#template tagging
app_name = 'kiran'

urlpatterns = [
    path('url',views.relative_url_temp,name='relative'),
    path('other',views.other,name='other'),

]

django/urlCoading_django_project/myUrl/myUrl/urls.py
from django.contrib import admin
from django.urls import path,include
from codingUrl import views


urlpatterns = [
    path('',views.index,name= 'home'),
    path('myapp/',include('codingUrl.urls')),
    path('admin/', admin.site.urls),
]

django/urlCoading_django_project/myUrl/codingUrl/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'my_templates/index.html')

def other(request):
    c = {"mydesc" : "hi kiran whatsssuuuppppp man"}
    return render(request,'my_templates/other.html',context=c)

def relative_url_temp(request):
    return render(request,'my_templates/relative_url_template.html')

django/urlCoading_django_project/myUrl/templates/my_templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block my_title %}
        Base
        {%endblock%}
    </title> 
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li><a class="navbar-brand" href="{% url 'home' %}">BRAND</a></li>
                <li><a class=" nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class=" nav-link" href="{% url 'kiran:other'%}">Other</a></li>
            </ul>
        </div>
      </nav>

      <div class="container">
          {% block my_block %}
        <h1>this is base page</h1>
          {% endblock %}
      </div>
</body>
</html>

django/urlCoading_django_project/myUrl/templates/my_templates/index.html
<!DOCTYPE html>
{% extends "my_templates/base.html" %}
<title>{% block my_title %}
    HOME
    {%endblock%}
</title> 
<body>
    {% block my_block %}
    <h1>WELCOME TO INDEX PAGE</h1>
    {%endblock%}
    
</body>
</html>

django/urlCoading_django_project/myUrl/templates/my_templates/other.html
<!DOCTYPE html>
{% extends "my_templates/base.html" %}
{% load my_cust_filter %}
<title>{% block my_title %}
    other
    {%endblock%}
</title> 
<body>
    {% block my_block %}
    
    <h1>WELCOME TO OTHER PAGE</h1>
    {{mydesc|upper}}
    <br>
    {{mydesc|cut:'kiran'}}
    <br>
    {{mydesc|sep:'kiran'}}
    {% endblock %}
    
</body>
</html>

django/urlCoading_django_project/myUrl/templates/my_templates/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RUT</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATE PAGE</h1>
    
</body>
</html>