django/password_Validation/myPass/myPass/urls.py
from django.contrib import admin
from django.urls import path,include
from validPass import views

urlpatterns = [
    path('',views.index,name='index'),
    path('spl/',views.special,name='spl'),
    path('register/',include('validPass.urls'),name='regi1'),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout')
    
]

django/password_Validation/myPass/validPass/urls.py
from django.urls import path
from validPass import views

app_name = 'myValidPass'

urlpatterns = [
    path('',views.register,name='regi'),
    path('login/',views.userLogin,name='myLogin')
]

django/password_Validation/myPass/validPass/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileDetails(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True,upload_to="myProfilePic")
    
    def __str__(self):
        return self.user.username
 

django/password_Validation/myPass/validPass/forms.py
from django import forms
from django.contrib.auth.models import User
from validPass.models import UserProfileDetails


class myForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfileDetails
        fields = ('portfolio_site','profile_pic')

django/password_Validation/myPass/validPass/views.py
from django.shortcuts import render
from validPass.forms import myForm,UserProfileForm


from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect



# Create your views here.
def index(request):
    return render(request,'myTemp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Hi bvs")

    

def register(request):
    registered = False
    if request.method == 'POST':
    
        userDetails =  myForm(data=request.POST)
        print("userDetails : ",userDetails,end="")
        
        portfolioDetails = UserProfileForm(data=request.POST)
        print("portfolioDetails : " , portfolioDetails,end="")
        

        if userDetails.is_valid() and portfolioDetails.is_valid():
            
            newUser = userDetails.save()
            print("newUser : ",newUser,end="")
            newUser.set_password(newUser.password)
            newUser.save()
            
            profile = portfolioDetails.save(commit=False)
            profile.user = newUser
           
            print("profile : " , type(profile),end="")

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()
            print()
            print()
            print()
            print("profile : " , profile,end="")

            registered = True
        
        else:
            print(userDetails.errors,portfolioDetails.errors)
         
    else:
        userDetails = myForm()
        portfolioDetails = UserProfileForm()

    return render(request,'myTemp/registration.html',
                                                context={
                                                'regForm' :userDetails,
                                                'ppForm':portfolioDetails,
                                                'registered':registered
                                                })

    
def userLogin(request):

    if request.method == 'POST':
        userName = request.POST.get('username')
        passWord = request.POST.get('password')

        user = authenticate(username=userName,password=passWord)
        print()
        print(user)
        print()
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("gone gone ")
            return HttpResponse("invalid user name : {} and password : {}".format(userName,passWord))
    else:
        return render(request,'myTemp/login.html',{})

django/password_Validation/myPass/myPass/templates/myTemp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="navbar-brand" href="{%url 'index' %}">Django</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'myValidPass:regi' %}">Registration</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {%else%}
                <li class="nav-item"><a class="nav-link" href="{% url 'myValidPass:myLogin' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
        <div class="container">
        {% block mybase %}
        {% endblock %}
        </div>
</body>
</html>

django/password_Validation/myPass/myPass/templates/myTemp/index.html
{% extends "myTemp/base.html" %}

{% block mybase %}

<div class="jumbotron">
<h1>Django level five</h1>
</div>
{% endblock %}

django/password_Validation/myPass/myPass/templates/myTemp/login.html
{% extends 'myTemp/base.html' %}

{% block mybase%}

<div class="jumbotron">
<h1>Please Login</h1>

<form  action="{% url 'myValidPass:myLogin' %}" method="POST">
    {% csrf_token %}
    <label for="username">UserName :</label>
    <input type="text" name="username" placeholder="Enter user name here">
    <label for="username">Password :</label>
    <input type="password" name="password">
    <input type="submit" value="Login">
</form>
</div>

{% endblock %}

django/password_Validation/myPass/myPass/templates/myTemp/registration.html
{% extends "myTemp/base.html" %}
{% load static %}
{% block mybase %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for Registering</h1>

    {%else%}
    <h1>Register here!!!</h1>
    <h3>Fill the form</h3>

    <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ regForm.as_p }}
    {{ ppForm.as_p }}
    <input type="submit" value="Register">
    {% endif %}
    </form>

</div>

{% endblock %}